services:
  notification-db:
    image: postgres:16-alpine
    container_name: campuscare-notification-db
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: campuscare_notification
    ports:
      - "5435:5432"
    volumes:
      - notification-db-data:/var/lib/postgresql/data

  activemq:
    image: apache/activemq-artemis:latest-alpine
    container_name: campuscare-activemq
    restart: unless-stopped
    environment:
      ARTEMIS_USER: admin
      ARTEMIS_PASSWORD: admin
    ports:
      - "61616:61616"
      - "61613:61613"
      - "8161:8161"

  notification-service:
    build:
      context: ./apps/notification-service
    container_name: campuscare-notification-service
    restart: unless-stopped
    depends_on:
      - notification-db
      - activemq
    environment:
      PORT: 3003
      DATABASE_URL: postgresql://postgres:postgres@notification-db:5432/campuscare_notification?schema=public
      ACTIVEMQ_HOST: activemq
      ACTIVEMQ_STOMP_PORT: 61613
      ACTIVEMQ_USER: admin
      ACTIVEMQ_PASSWORD: admin
      ADMIN_BROADCAST_USER_ID: ADMIN_BROADCAST
    ports:
      - "3003:3003"

volumes:
  notification-db-data:
